version: "3.9"
services:
  alldaydj-localstack:
    image: localstack/localstack
    ports:
      - "4572:4572"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=eu-west-1
      - AWS_DEFAULT_REGION=eu-west-1
      - HOSTNAME_EXTERNAL=localhost
      - USE_SSL=false
      - DATA_DIR=/tmp/localstack/data
      - DEBUG=1
    volumes:
      - "alldaydj-localstack:/tmp/localstack"
  alldaydj-postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${ADDJ_DB_USER}
      - POSTGRES_PASSWORD=${ADDJ_DB_PASS}
      - POSTGRES_DB=${ADDJ_DB_NAME}
    volumes:
      - alldaydj-postgres:/var/lib/postgresql/data
  alldaydj-rabbit:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=${ADDJ_RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${ADDJ_RABBIT_PASS}
  alldaydj-web:
    image: steelegbr/alldaydj-web-backend:${GIT_BRANCH}
    ports:
      - 8000:8000
    environment:
      - ADDJ_SECRET_KEY
      - ADDJ_DEBUG
      - ADDJ_DB_NAME
      - ADDJ_DB_USER
      - ADDJ_DB_PASS
      - ADDJ_DB_HOST
      - ADDJ_USERS_DOMAIN
      - ADDJ_RABBIT_HOST
      - ADDJ_RABBIT_USER
      - ADDJ_RABBIT_PASS
      - ADDJ_CELERY_ALWAYS_EAGER
      - ADDJ_S3_REGION
      - ADDJ_S3_ENDPOINT
      - ADDJ_S3_KEY_ID
      - ADDJ_S3_KEY_SECRET
      - ADDJ_S3_BUCKET
    links:
      - alldaydj-postgres:postgres
      - alldaydj-rabbit:rabbit
      - alldaydj-localstack:localstack
  alldaydj-job-runner:
    image: steelegbr/alldaydj-job-runner:${GIT_BRANCH}
    environment:
      - ADDJ_SECRET_KEY
      - ADDJ_DEBUG
      - ADDJ_DB_NAME
      - ADDJ_DB_USER
      - ADDJ_DB_PASS
      - ADDJ_DB_HOST
      - ADDJ_USERS_DOMAIN
      - ADDJ_RABBIT_HOST
      - ADDJ_RABBIT_USER
      - ADDJ_RABBIT_PASS
      - ADDJ_CELERY_ALWAYS_EAGER
      - ADDJ_S3_REGION
      - ADDJ_S3_ENDPOINT
      - ADDJ_S3_KEY_ID
      - ADDJ_S3_KEY_SECRET
      - ADDJ_S3_BUCKET
      - CELERY_BROKER_URL=amqp://${ADDJ_RABBIT_USER}:${ADDJ_RABBIT_PASS}@rabbit:5672/
    links:
      - alldaydj-postgres:postgres
      - alldaydj-rabbit:rabbit
      - alldaydj-localstack:localstack
volumes:
  alldaydj-localstack:
  alldaydj-postgres: